version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exampledb
    volumes:
      - ./docker-compose/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro,z