spring:
  cloud:
    #function:
    #  # Only required when more than one top-level bean defined
    #  definition: 'processor'
    stream:
      bindings:
        handler-in-0.destination: 'profiles'
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    username: 'testusername'
    password: 'testpassword'
  flyway:
    placeholders:
      username: '${spring.datasource.username}'
      password: '${spring.datasource.password}'