spring:
  # See https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.messaging.jms.artemis
  artemis:
    mode: 'native'
  datasource:
    driver-class-name: 'org.postgresql.Driver'
  flyway:
    placeholders:
      username: '${spring.datasource.username}'
      password: '${spring.datasource.password}'