CREATE USER username WITH PASSWORD 'password';
GRANT CONNECT ON DATABASE ${flyway:database} TO username;
GRANT USAGE ON SCHEMA public TO username;
ALTER DEFAULT PRIVILEGES
  FOR USER username
  IN SCHEMA public
  GRANT ALL ON TABLES TO username;
ALTER DEFAULT PRIVILEGES
  FOR USER username
  IN SCHEMA public
  GRANT ALL ON SEQUENCES TO username;