CREATE USER ${username} WITH PASSWORD '${password}';
ALTER DEFAULT PRIVILEGES
  IN SCHEMA public
  GRANT ALL ON TABLES TO ${username};
ALTER DEFAULT PRIVILEGES
  IN SCHEMA PUBLIC
  GRANT ALL ON SEQUENCES TO ${username};
